#!/usr/bin/env php
<?php

require __DIR__ .'/vendor/autoload.php';
require __DIR__ .'/config/database.php';

use Illuminate\Database\Capsule\Manager as Capsule;
use Cartalyst\Sentinel\Native\Facades\Sentinel;

class Migrator {

    /**
     * migrate the database schema
     */
    public function migrate() {
			/**
 * La table Createur
 */
if (!Capsule::schema()->hasTable('Createur')) {
		Capsule::schema()->create('Createur', function($table)
		{
				$table->integer('id', true);
				$table->string('nom');
				$table->string('prenom');
				$table->string('email');
				$table->string('login');
				$table->string('password');
				$table->string('token')->nullable();
				$table->timestamps();
				// We'll need to ensure that MySQL uses the InnoDB engine to
				// support the indexes, other engines aren't affected.
				$table->engine = 'InnoDB';

				$table->unique('email');
		});
}
/**
 * La table liste
 */
if (!Capsule::schema()->hasTable('Liste')) {
		Capsule::schema()->create('Liste', function($table)
		{
				$table->integer('token', true);
				$table->integer('user_id');
				$table->integer('total_price')->default(0);
				$table->timestamp('order_date');
				$table->timestamps();
				// We'll need to ensure that MySQL uses the InnoDB engine to
				// support the indexes, other engines aren't affected.
				$table->engine = 'InnoDB';
				//Foreign keys
				$table->foreign('user_id')->references('id')->on('User');
		});
}
    }

    /**
     * seed the database with initial value
     */
    public function seed() {
        try {
           $credentials = [
				// 'email'    => 'admin@admin.com',
				// 'password' => 'password',
				// 'first_name' => 'Yudi',
				// 'last_name' => 'Purwanto',
			];

			$user = Sentinel::registerAndActivate($credentials);

        } catch(Exception $e) {
            echo $e->getMessage()."\n";
        }
    }
}

$migrator = new Migrator();

$migrator->migrate();
// $migrator->seed();

print("Migration Successfully");
