#!/usr/bin/env php
<?php

require __DIR__ .'/vendor/autoload.php';
require __DIR__ .'/config/database.php';

use Illuminate\Database\Capsule\Manager as Capsule;
use Cartalyst\Sentinel\Native\Facades\Sentinel;

class Migrator {
	
    /**
     * migrate the database schema
     */
    public function migrate() {
       
    }

    /**
     * seed the database with initial value
     */
    public function seed() {
        try {
           $credentials = [
				// 'email'    => 'admin@admin.com',
				// 'password' => 'password',
				// 'first_name' => 'Yudi',
				// 'last_name' => 'Purwanto',
			];

			$user = Sentinel::registerAndActivate($credentials);
			
        } catch(Exception $e) {
            echo $e->getMessage()."\n";
        }
    }
}

$migrator = new Migrator();

$migrator->migrate();
// $migrator->seed();

print("Migration Successfully");