#!/usr/bin/env php
<?php

require __DIR__ .'/vendor/autoload.php';
require __DIR__ .'/config/database.php';

use Illuminate\Database\Capsule\Manager as Capsule;
use Cartalyst\Sentinel\Native\Facades\Sentinel;

class Migrator {

    /**
     * migrate the database schema
     */
    public function migrate() {
        /**
         * La table Createur
         */
        if (!Capsule::schema()->hasTable('Createur')) {
            Capsule::schema()->create('Createur', function($table)
            {

                $table->integer('id', true);
                $table->string('nom');
                $table->string('prenom')->nullable();
                $table->string('email');
                $table->string('login');
                $table->string('password');
                $table->string('token')->nullable();
                $table->timestamps();

                // We'll need to ensure that MySQL uses the InnoDB engine to
                // support the indexes, other engines aren't affected.
                $table->engine = 'InnoDB';

                $table->unique('email');
            });
        }

        /**
         * La table liste
         */
        if (!Capsule::schema()->hasTable('Liste')) {
            Capsule::schema()->create('Liste', function($table)
            {
                $table->integer('id', true);
                $table->integer('createur_id');
                $table->string('token');
                $table->string('nom');
                $table->text('description');
                $table->date('date_val');
                $table->string('destinataire');
                $table->timestamps();

                // We'll need to ensure that MySQL uses the InnoDB engine to
                // support the indexes, other engines aren't affected.
                $table->engine = 'InnoDB';
                $table->unique('token');

                //Foreign keys
                $table->foreign('createur_id')->references('id')->on('Createur');

            });
        }

        /**
         * La table item
         */
        if (!Capsule::schema()->hasTable('Item')) {
            Capsule::schema()->create('Item', function($table)
            {
                $table->integer('id', true);
                $table->string('liste_token');
                $table->string('nom');
                $table->text('description');
                $table->string('lien_image');
                $table->string('lien_url');
                $table->integer('tarif');
                $table->timestamps();

                // We'll need to ensure that MySQL uses the InnoDB engine to
                // support the indexes, other engines aren't affected.
                $table->engine = 'InnoDB';

                 //Foreign keys
                $table->foreign('liste_token')->references('token')->on('Liste');
            });
        }

        /**
         * la table Commentaire_liste
         */
        if (!Capsule::schema()->hasTable('Commentaire_liste')) {
            Capsule::schema()->create('Commentaire_liste', function($table)
            {
                $table->integer('id', true);
                $table->integer('liste_id');
                $table->string('nom');
                $table->text('message');
                $table->timestamps();

                // We'll need to ensure that MySQL uses the InnoDB engine to
                // support the indexes, other engines aren't affected.
                $table->engine = 'InnoDB';

                //Foreign keys
                $table->foreign('liste_id')->references('id')->on('Liste');
            });
        }

        /**
         * La table commentaire_item
         */
        if (!Capsule::schema()->hasTable('Commentaire_item')) {
            Capsule::schema()->create('Commentaire_item', function($table)
            {
                $table->integer('id', true);
                $table->integer('item_id');
                $table->string('nom');
                $table->string('message');
                $table->timestamps();

                // We'll need to ensure that MySQL uses the InnoDB engine to
                // support the indexes, other engines aren't affected.
                $table->engine = 'InnoDB';

                //Foreign keys
                $table->foreign('item_id')->references('id')->on('Item');

            });
        }
    }

    /**
     * seed the database with initial value
     */
    public function seed() {
        try {
           $credentials = [
				// 'email'    => 'admin@admin.com',
				// 'password' => 'password',
				// 'first_name' => 'Yudi',
				// 'last_name' => 'Purwanto',
			];

			$user = Sentinel::registerAndActivate($credentials);

        } catch(Exception $e) {
            echo $e->getMessage()."\n";
        }
    }
}

$migrator = new Migrator();

$migrator->migrate();
// $migrator->seed();

print("Migration Successfully");
